import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Every path the agent touches, resolved once from the repo root.
 *
 * Nothing else in the codebase joins paths against the repo root, so a
 * relocated directory is a one-line change here.
 */
export interface RepoPaths {
  /** Repo root — the directory holding contentlayer.config.ts */
  root: string
  /** Agent package root (tools/blog-agent) */
  agent: string
  /** Published and draft posts */
  blog: string
  /** Author profiles; frontmatter `authors` entries must resolve here */
  authors: string
  /** Public asset root. Image URLs in MDX are relative to this. */
  publicDir: string
  /** Hero images live in <blogImages>/<key>/hero.png */
  blogImages: string
  /** Git-tracked tag counts, regenerated by the contentlayer build */
  tagData: string
  /** Contentlayer output; the MDX gate asserts against this */
  generated: string
  /** Per-run debug output, gitignored */
  artifacts: string
}

const AGENT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')

/**
 * Walk up from the agent package looking for the marker file that identifies
 * the blog repo root. Walking beats a hardcoded '../..' because it keeps
 * working when the agent is invoked through a symlink or a git worktree.
 */
function findRepoRoot(start: string): string {
  let dir = start
  for (let i = 0; i < 10; i++) {
    if (existsSync(path.join(dir, 'contentlayer.config.ts'))) return dir
    const parent = path.dirname(dir)
    if (parent === dir) break
    dir = parent
  }
  throw new Error(
    `Could not locate the blog repo root above ${start} ` +
      `(looked for contentlayer.config.ts). Run the agent from inside the repo.`
  )
}

export function resolvePaths(repoRoot = findRepoRoot(AGENT_DIR)): RepoPaths {
  return {
    root: repoRoot,
    agent: AGENT_DIR,
    blog: path.join(repoRoot, 'data', 'blog'),
    authors: path.join(repoRoot, 'data', 'authors'),
    publicDir: path.join(repoRoot, 'public'),
    blogImages: path.join(repoRoot, 'public', 'static', 'images', 'blog'),
    tagData: path.join(repoRoot, 'app', 'tag-data.json'),
    generated: path.join(repoRoot, '.contentlayer', 'generated'),
    artifacts: path.join(AGENT_DIR, '.artifacts'),
  }
}

export const paths = resolvePaths()
