import { execFile } from 'node:child_process'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { promisify } from 'node:util'

import type { Logger } from '../lib/logger.js'
import type { GateReport } from '../gates/types.js'
import { renderReport } from '../gates/run.js'
import { makeGit } from './git.js'

const exec = promisify(execFile)

/**
 * Creates the post branch and opens the PR.
 *
 * The branch name carries the run id. Without it, a retry after a partial
 * failure pushes to the same branch as a live PR and either rejects or
 * force-clobbers a review in progress.
 */

export interface PublishInput {
  repoRoot: string
  slug: string
  runId: string
  branchPrefix: string
  title: string
  /** Final post bytes, already Prettier-formatted and gate-approved. */
  source: string
  /** Repo-relative destination for the post. */
  postPath: string
  /** Hero image and any other assets: repo-relative path -> bytes. */
  assets: ReadonlyMap<string, Buffer>
  /** Regenerated app/tag-data.json from the compile gate, if it changed. */
  tagData?: string
  report: GateReport
  sources: readonly string[]
  logger: Logger
}

export interface PublishResult {
  branch: string
  prNumber?: number
  prUrl?: string
}

export function branchNameFor(prefix: string, slug: string, runId: string): string {
  return `${prefix}${slug}-${runId}`
}

/**
 * Runs Prettier over the post before the gates see it.
 *
 * The repo's husky pre-commit hook runs `prettier --write` on staged `*.mdx`,
 * which reflows paragraphs, renumbers lists, and rewrites frontmatter quoting.
 * If that happens at commit time, the bytes that passed the gates are not the
 * bytes that land in the PR. Formatting first — and committing with
 * `--no-verify` — makes the validated bytes authoritative.
 */
export async function formatMdx(repoRoot: string, source: string, logger: Logger): Promise<string> {
  const tmp = path.join(repoRoot, `.blog-agent-format-${process.pid}.mdx`)
  try {
    await writeFile(tmp, source, 'utf8')
    await exec('npx', ['prettier', '--write', tmp], { cwd: repoRoot, maxBuffer: 16 * 1024 * 1024 })
    const { stdout } = await exec('cat', [tmp])
    return stdout
  } catch (cause) {
    // Formatting is a normalisation step, not a correctness gate. If Prettier
    // is unavailable the post is still valid; it will simply be reformatted by
    // the hook later, so warn rather than failing the run.
    logger.warn('prettier unavailable; committing unformatted', {
      err: cause instanceof Error ? cause.message : String(cause),
    })
    return source
  } finally {
    await exec('rm', ['-f', tmp]).catch(() => {})
  }
}

export async function publishPost(input: PublishInput): Promise<PublishResult> {
  const { repoRoot, slug, runId, logger } = input
  const log = logger.child({ component: 'publish' })
  const git = makeGit(repoRoot, logger)
  const branch = branchNameFor(input.branchPrefix, slug, runId)

  const baseBranch = (await git(['rev-parse', '--abbrev-ref', 'HEAD'])) || 'main'
  const startPoint = await git(['rev-parse', 'HEAD'])

  await git(['checkout', '-q', '-b', branch, startPoint])

  try {
    const postFile = path.join(repoRoot, input.postPath)
    await mkdir(path.dirname(postFile), { recursive: true })
    await writeFile(postFile, input.source, 'utf8')

    for (const [rel, bytes] of input.assets) {
      const dest = path.join(repoRoot, rel)
      await mkdir(path.dirname(dest), { recursive: true })
      await writeFile(dest, bytes)
    }

    await git(['add', input.postPath])
    for (const rel of input.assets.keys()) await git(['add', rel])

    // --no-verify: husky's lint-staged would reformat the .mdx we just
    // validated. Prettier already ran, before the gates.
    await git(['commit', '-q', '--no-verify', '-m', commitMessage(input)])
    await git(['push', '-q', '--set-upstream', 'origin', branch])
    log.info('pushed post branch', { branch })

    const pr = await openPullRequest({ ...input, branch, baseBranch })
    return pr ? { branch, ...pr } : { branch }
  } finally {
    await git(['checkout', '-q', baseBranch], { allowFail: true })
  }
}

function commitMessage(input: PublishInput): string {
  return [
    `content: ${input.title}`,
    '',
    `Generated by blog-agent (run ${input.runId}).`,
    `Gates: ${input.report.errors.length} error(s), ${input.report.warnings.length} warning(s).`,
  ].join('\n')
}

async function openPullRequest(
  input: PublishInput & { branch: string; baseBranch: string }
): Promise<{ prNumber: number; prUrl: string } | null> {
  const log = input.logger.child({ component: 'publish.pr' })
  const body = renderPrBody(input)

  try {
    const { stdout } = await exec(
      'gh',
      [
        'pr',
        'create',
        '--base',
        input.baseBranch,
        '--head',
        input.branch,
        '--title',
        input.title,
        '--body',
        body,
      ],
      { cwd: input.repoRoot, maxBuffer: 8 * 1024 * 1024 }
    )
    const url = stdout.trim().split('\n').pop() ?? ''
    const number = Number(/\/pull\/(\d+)/.exec(url)?.[1] ?? '0')
    log.info('opened pull request', { url, number })
    return number > 0 ? { prNumber: number, prUrl: url } : null
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : String(cause)
    if (/not authorized|403|GraphQL: GitHub Actions is not permitted/i.test(message)) {
      // Worth naming precisely: this setting is off by default in many orgs and
      // the raw error does not say which one to flip.
      throw new Error(
        `gh pr create was refused. Enable Settings -> Actions -> General -> ` +
          `"Allow GitHub Actions to create and approve pull requests", or supply a ` +
          `fine-grained PAT as GITHUB_TOKEN. Original: ${message}`
      )
    }
    throw cause
  }
}

export function renderPrBody(input: {
  slug: string
  runId: string
  report: GateReport
  sources: readonly string[]
}): string {
  const lines = [
    '## Generated post',
    '',
    `Slug: \`${input.slug}\``,
    `Run: \`${input.runId}\``,
    '',
    '### Validation',
    '',
    renderReport(input.report),
    '',
  ]
  if (input.sources.length > 0) {
    lines.push('### Sources consulted', '')
    for (const s of input.sources.slice(0, 20)) lines.push(`- ${s}`)
    lines.push('')
  }
  lines.push(
    '---',
    '',
    'Generated by `tools/blog-agent`. Review the prose and the cited sources before merging —',
    'the gates verify structure, links, and that the post compiles, not that the claims are true.'
  )
  return lines.join('\n')
}
